language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit --configuration="phpunit.xml" --include-path="tests"

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always