language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  #- hhvm
  #- nightly

# Commands to be run before your environment runs.
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

# Commands you want to run that will verify your build.
script:
    - phpunit

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
